services:
  - type: web
    name: exam-seating-backend
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx512M -jar target/exam-seating-1.0.0.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d7qu2ld7vvec73e06pbg-a:5432/exam_seating_db_53ux
      - key: SPRING_DATASOURCE_USERNAME
        value: exam_seating_db_53ux_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: mWH6HrByQGfTySZZGjkJkNcyxKyVUk8a
